name: "create env var"
description: "export env var composite action"
outputs:
  DEPLOY_ENV:
    description: "Deploy Env"
    value: ${{ steps.export-env-var.outputs.DEPLOY_ENV}}
runs:
  using: "composite"
  steps:
    - run: echo "DEPLOY_ENV=$(if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then echo '${{ github.event.inputs.env }}'; else echo 'staging'; fi)" >> $GITHUB_ENV
      shell: bash
    - id: export-env-var
      run: echo "::set-output name=DEPLOY_ENV::$DEPLOY_ENV"
      shell: bash
    - run: echo $DEPLOY_ENV
      shell: bash
