name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: building
        run: echo Building bla
        shell: bash
  tagg:
    runs-on: ubuntu-latest
    steps:
      - name: create DEPLOY_ENV
        run: echo "DEPLOY_ENV=$(if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then echo '${{ github.event.inputs.env }}'; else echo 'staging'; fi)" >> $GITHUB_ENV
      - id: export-env-var
        run: echo "::set-output name=DEPLOY_ENV::$DEPLOY_ENV"
      - name: print deploy env
        run: echo $DEPLOY_ENV
    outputs:
      DEPLOY_ENV: ${{ steps.export-env-var.outputs.DEPLOY_ENV }}
  check:
    runs-on: ubuntu-latest
    steps:
      - name: print deploy env
        run: echo "deploy ${{needs.tagg.outputs.DEPLOY_ENV}}"

