name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: building
        run: echo Building bla
        shell: bash
  tagg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - id: get-var
        uses: ./.github/workflows/create-env-var
    outputs:
      DEPLOY_ENV: ${{ steps.get-var.outputs.DEPLOY_ENV }}
  check:
    runs-on: ubuntu-latest
    needs: tagg
    steps:
      - name: print deploy env
        run: echo "deploy ${{needs.tagg.outputs.DEPLOY_ENV}}"

