name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: building
        run: echo Building bla
        shell: bash
  tagg:
    runs-on: ubuntu-latest
    steps:
      - name: get var
        uses: ./github/workflows/create-env-var
  check:
    runs-on: ubuntu-latest
    needs: tagg
    steps:
      - name: print deploy env
        run: echo "deploy ${{needs.tagg.outputs.DEPLOY_ENV}}"

