name: Bump version
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        options:
        - staging
        - prod
        default: staging
      bump:
        type: choice
        required: false
        options:
        - patch
        - minor
        - major
        default: patch
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: building
        run: echo Building bla
        shell: bash
  tagg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - id: get-var
        uses: ./.github/workflows/create-env-var
    outputs:
      DEPLOY_ENV: ${{ steps.get-var.outputs.DEPLOY_ENV }}
  check:
    runs-on: ubuntu-latest
    needs: tagg
    steps:
      - name: print deploy env
        run: echo "deploy ${{needs.tagg.outputs.DEPLOY_ENV}}"
      - name: Create tag
        # If an existing tag hasn't been chosen - create a new one (only when running manual)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "${{ env.DEPLOY_ENV }}-gprofiler-worker-and-collapser-"
          default_bump: ${{ github.event.inputs.bump }}

