name: gProfiler WebApp CD

on:
  push:
    branches:
     - master
    paths:
      - 'src/gprofiler/**'
      - 'src/gprofiler-dev/**'
  workflow_dispatch:
    inputs:
      env: 
        type: choice
        required: true
        options:
        - staging
        - demo
        - prod
        default: staging
      bump:
        description: 'Bump Type (choose value only if you did not choose an existing tag)'
        type: choice
        options: 
        - patch
        - minor
        - major
    branches:
      - master
      - hotfix/**

jobs:
  docker-build:
    runs-on:
     - self-hosted
     - granulate-ci-cd
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: sudo git lfs checkout
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        run: ./src/gprofiler/docker_build.sh
        env:
          TAG: ${{github.sha}}
          GIT_SSH_KEY_FOR_GRANULATE_PRIVATE_REPOS: ${{ secrets.GIT_SSH_KEY_FOR_GRANULATE_PRIVATE_REPOS }}
      - id: get-var
        uses: ./.github/workflows/create-env-var
    outputs:
      DEPLOY_ENV: ${{ steps.get-var.outputs.DEPLOY_ENV }}

  deploy:
    needs: docker-build
    runs-on:
     - self-hosted
     - granulate-ci-cd
    environment: "${{ needs.docker-build.outputs.DEPLOY_ENV }}-cd"
    env:
      DEPLOY_ENV: ${{ needs.docker-build.outputs.DEPLOY_ENV }}
    steps:
      - name: Pull latest granulate
        working-directory: /code/src/github.com/Granulate/granulate
        run: sudo git checkout master && sudo git pull
      - name: Deploy WebApp
        uses: ./../../../../../../code/src/github.com/Granulate/granulate/ops/github-actions/deploy
        with:
          env: ${{ env.DEPLOY_ENV }}
          service: gprofiler-webapp
      - name: Deploy Agents backend
        if: ${{ env.DEPLOY_ENV == 'prod' }}
        uses: ./../../../../../../code/src/github.com/Granulate/granulate/ops/github-actions/deploy
        with:
          env: ${{ env.DEPLOY_ENV }}
          service: gprofiler-agents-backend
      - name: check bump
        run: echo bump is ${{ github.event.inputs.bump }}
      - name: Create tag
        # If an existing tag hasn't been chosen - create a new one
        if: ${{ !startsWith(github.ref, 'refs/tags/') && github.event_name == 'workflow_dispatch' }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "${{ env.DEPLOY_ENV }}-gprofiler-worker-and-collapser-"
          default_bump: ${{ github.event.inputs.bump }}
          
#       - name: Slack Notify
#         if: ${{ always() }}
#         uses: rtCamp/action-slack-notify@v2.2.0
#         env:
#           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#           SLACK_MESSAGE: gProfiler WebApp is ${{ job.status }} to deploy to ${{ env.DEPLOY_ENV }}
#           SLACK_COLOR: ${{ job.status }}
#           SLACK_USERNAME: CICD
#           SLACK_ICON: https://avatars.githubusercontent.com/u/43335248?s=200&v=4
