name: Deploy prod with new tag
on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Bump Type'
        type: choice
        required: true
        options: 
        - patch
        - minor
        - major
      environment:
        type: environment
      
      
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: building
        run: echo Building bla
        shell: bash
  tag:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "manual-"
          default_bump: ${{ github.event.inputs.bump }}
#       - name: Create a GitHub release
#         uses: ncipollo/release-action@v1
#         with:
#           tag: ${{ github.event.inputs.tag }}
#           name: Release ${{ github.event.inputs.tag }} 
          
