name: Deploy prod with new tag
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        default: 'Staging'
      bump:
        description: 'Bump Type (choose value only if you did not choose a tag)'
        type: choice
        options: 
        - patch
        - minor
        - major
      
      
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: building
        run: echo ${{ github.ref }}
        shell: bash
  tag:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "${{ github.event.inputs.environment }}-"
          default_bump: ${{ github.event.inputs.bump }}
#       - name: Create a GitHub release
#         uses: ncipollo/release-action@v1
#         with:
#           tag: ${{ github.event.inputs.tag }}
#           name: Release ${{ github.event.inputs.tag }} 
          
