name: test annotated tag
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag if not chosen
        # If an existing tag hasn't been chosen - create a new one (only when running manual)
        if: ${{ !startsWith(github.ref, 'refs/tags/') && github.event_name == 'workflow_dispatch' }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "bla-test-v"
          default_bump: "minor"
          create_annotated_tag: true
          # Next line is important so tagging will work with bumps correctly
